[package]
name = "container-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23"
libc = "0.2.153"
clap = {version = "4.5.0", features=["derive"]}
dotenv = "0.15.0"
